double quote ALL THE THINGS!!!

diff --git a/.github/actions/emit-metrics/action.yml b/.github/actions/emit-metrics/action.yml
--- a/.github/actions/emit-metrics/action.yml
+++ b/.github/actions/emit-metrics/action.yml
@@ -42,7 +42,7 @@ runs:
   steps:
     - name: Verify kat exists
       shell: bash
-      run: which kat || ( echo Cannot find kat installation. Did you forget to run setup-kat first? && exit 1 )
+      run: which kat || ( echo "Cannot find kat installation. Did you forget to run setup-kat first?" && exit 1 )
     - name: Emit Metrics
       shell: bash
       run: |
